apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
spec:
  project: default  # ✅ Add this line to specify the project
  source:
    repoURL: 'https://github.com/Puun2545/Pipeline-Test-Interview.git'
    targetRevision: HEAD
    path: 'path-to-k8s-manifests'  # Update this with the correct path in your repo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nodejs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
