apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # หรือใช้ "elb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
