name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - "v1.0.0"  # รองรับการ Push Tag เช่น v1.0.0

env:
  IMAGE_NAME: puunvach/nodejs-app

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ github.ref_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Define Image Tag
        id: set_tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG_VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Debug - Show TAG_VERSION
        run: echo "Tag Version = $TAG_VERSION"
  
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          cd src
          docker build -t puunvach/nodejs-app:${{ env.TAG_VERSION }} .
          docker push puunvach/nodejs-app:${{ env.TAG_VERSION }}


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # ดึงทุกไฟล์จาก Git

      - name: Update Image in Kubernetes Manifest
        run: |
          sed -i 's|puunvach/nodejs-app:.*|puunvach/nodejs-app:${{ env.TAG_VERSION }}|' k8s/deployment.yaml

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image to puunvach/nodejs-app:${{ env.TAG_VERSION }}"
          git push

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: Verify ArgoCD CLI
        run: argocd version --client
  
      - name: Debug - List files
        run: ls -R

      - name: Set Execute Permission for Script
        run: chmod +x scripts/deploy-argo.sh

      - name: Run Deployment Script
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        run: scripts/deploy-argo.sh


